name: Python Tests

on: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name:
    #   uses: 
    #   with:

    # - name:
    #   run: 
