name: Python Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Run tests with pytest
      uses: oNaiPs/secrets-to-env-action@v1
      with:
          secrets: ${{ toJSON(secrets) }}
    - run: |
        pytest ./test_api/test_api_login.py

    - name: Collect Logs
      id: collect-logs
      uses: ./.github/actions/collect-logs

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      with:
        name: workflow-logs
        path: ${{ steps.collect-logs.outputs.logs-path }}
